/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RomanTest {

    @Test
    public void testConverter() {
        assertEquals("IV", RomanConverter.getRomanFromNumber(4));
        assertThrows(IllegalArgumentException.class, () -> RomanConverter.getRomanFromNumber(-2));
    }

    // TODO : les autres tests
}
